[manifest]
id = "OSRAuto"
version = "1.0.0"
display_name = "Open Speed Run(OSR) Autosplitter"
description = "An autosplitter for OSR to be used in conjunction with the client in the github"
short_description = "An autosplitter for OSR to be used in conjunction with the client in the github"
authors = [ "Kazii The Avali" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "OSRAuto"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
